useMockData: true

server.port: 8080
spring.devtools.livereload.enabled: true

spring.cloud.stream.kafka.streams.binder.serdeError: logAndContinue

#org.springframework.kafka.support.serializer.JsonSerializer
#org.springframework.kafka.support.serializer.JsonDeserializer

kafka.topic.stocks.bigvolume: stocks.bigvolume

spring.kafka:
    bootstrap-servers: localhost:9092
    producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: stocks
      properties.spring.json.trusted.packages: com.stockinvest.server


