kafka:
  topic:
    boot: boot.greetings

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: boot
      properties:
        spring:
          json:
            trusted:
              packages: com.stockinvest.server

